# Generated by Django 4.2.7 on 2026-01-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Begginer', 'Begginer'), ('Intermidiate', 'Intermidiate'), ('Advance', 'Advance')], default='Begginer', max_length=100),
        ),
    ]
