# Generated by Django 4.2.7 on 2026-01-03 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_items', to='api.variant'),
        ),
    ]
