# Generated by Django 4.2.7 on 2026-01-03 12:50

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_variantitem_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdef123456789', length=6, max_length=20, prefix=''),
        ),
    ]
