# Generated by Django 4.2.7 on 2025-12-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_alter_customuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
